server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Qualsevol ruta que no sigui un fitxer real,
    # retorna index.html perquè Vue Router la gestioni
    location / {
        try_files $uri $uri/ /index.html;
    }
}